sudo: required
services:
  - docker

before_install:
  - docker build -t balazimichal/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run balazimichal/react-test npm test -- --coverage

after_success:
  - docker build -t balazimichal/multi-client ./client
  - docker build -t balazimichal/multi-nginx ./nginx
  - docker build -t balazimichal/multi-server ./server
  - docker build -t balazimichal/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push balazimichal/multi-client
  - docker push balazimichal/multi-nginx
  - docker push balazimichal/multi-server
  - docker push balazimichal/multi-worker

